### ISSUE TITLE
hashbangs

### ISSUE THREAD

**Issue by rhalff** [nicolashery/router-lib#2]
Is it possible to use  hashbangs like this http://localhost:8080/#!/items ?

If so, I do not know how to get it working :-)

**Comment by nicolashery** [comment]
Hey @rhalff, at this time `router-lib` only works with `http://localhost/#/items/123` style URLs.

Adding hashbangs, or even HTML5 pushstate (no hashes at all), is not something I had planned to add in the near future, sorry...

**Comment by rhalff** [comment]
It seems to work like a charm, I didn't call `router.start();`

The design of the lib seems to fit my use case very well, so thanks.

**Comment by nicolashery** [comment]
Glad it worked out for you!
